<?php declare(strict_types=1);
/**
 * Joomla! API Documentation
 *
 * @copyright  Copyright (C) 2018 Open Source Matters, Inc. All rights reserved.
 * @license    http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License Version 2 or Later
 */

namespace Joomla\ApiDocumentation\Importer;

use Joomla\ApiDocumentation\Model\Version;
use Joomla\ApiDocumentation\Repository\ClassRepository;

/**
 * Importer for the data dump generated by the parser process.
 */
final class ParsedDataImporter
{
	/**
	 * PHPClass model repository.
	 *
	 * @var  ClassRepository
	 */
	private $classRepository;

	/**
	 * Importer constructor.
	 *
	 * @param   ClassRepository  $classRepository  PHPClass model repository.
	 */
	public function __construct(ClassRepository $classRepository)
	{
		$this->classRepository = $classRepository;
	}

	/**
	 * Import the parsed data.
	 *
	 * @param   array    $data     The data to process.
	 * @param   Version  $version  The version to assign the imported data to.
	 *
	 * @return  void
	 */
	public function importData(array $data, Version $version): void
	{
		foreach ($data as $file)
		{
			foreach ($file['classes'] as $class)
			{
				$classModel = $this->classRepository->createOrUpdateFromClassNode($class, $version);
			}
		}
	}
}
